In [54]:
import pandas as pd

df = pd.DataFrame({
    "Student_ID": [
        101, 102, 103, 104, 105,
        106, 107, 108, 109, 110,
        111, 112, 113, 114, 115
    ],

    "Student_Name": [
        "Aarav", "Riya", "Neha", "Rahul", "Priya",
        "Aman", "Kavya", "Rohit", "Simran", "Vikas",
        "Anjali", "Karan", "Meera", "Arjun", "Nisha"
    ],

    "DOB": [
        "2006-01-15", "2005-03-20", "2006-06-10",
        "2005-09-25", "2006-02-12", "2005-11-30",
        "2006-04-18", "2005-07-22", "2006-08-05",
        "2005-12-17", "2006-10-28", "2005-05-11",
        "2006-12-20", "2005-01-08", "2006-07-14"
    ],

    "Admission_Date": [
        "2024-07-10", "2024-07-12", "2024-07-15",
        "2024-07-18", "2024-07-20", "2024-07-22",
        "2024-07-25", "2024-07-28", "2024-08-01",
        "2024-08-03", "2024-08-05", "2024-08-08",
        "2024-08-10", "2024-08-12", "2024-08-15"
    ],

    "Course": [
        "Python", "SQL", "Python", "Power BI", "SQL",
        "Python", "Excel", "Power BI", "Python", "SQL",
        "Excel", "Python", "Power BI", "SQL", "Python"
    ],

    "Marks": [
        78, 85, 92, 67, 74,
        88, 95, 61, 83, 72,
        90, 56, 81, 69, 97
    ],

    "Attendance": [
        92, 88, 95, 76, 84,
        91, 98, 72, 89, 81,
        94, 68, 87, 79, 96
    ],

    "Study_Hours": [
        3, 4, 5, 2, 3,
        4, 6, 2, 4, 3,
        5, 2, 4, 3, 6
    ],

    "Fees_Paid": [
        15000, 18000, 15000, 20000, 18000,
        15000, 12000, 20000, 15000, 18000,
        12000, 15000, 20000, 18000, 15000
    ]
})

df

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [55]:
df['DOB'] = pd.to_datetime(df['DOB'])

In [6]:
df['DOB'].dt.year

0     2006
1     2005
2     2006
3     2005
4     2006
5     2005
6     2006
7     2005
8     2006
9     2005
10    2006
11    2005
12    2006
13    2005
14    2006
Name: DOB, dtype: int32

In [8]:
df['Course'].unique()

array(['Python', 'SQL', 'Power BI', 'Excel'], dtype=object)

In [10]:
df['Course'].nunique()

4

In [12]:
df['Course'].value_counts()

Course
Python      6
SQL         4
Power BI    3
Excel       2
Name: count, dtype: int64

In [21]:
df.rename(columns = {'Marks' : 'Score'}, inplace = True)
df

,Student_ID,Student_Name,DOB,Admission_Date,Course,Score,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [27]:
df['Grade'] =  pd.cut(
df['Score'],
bins = [60, 80, 100],
labels = ['C', 'A' 'A+'])

df['Grade']

0       C
1     AA+
2     AA+
3       C
4       C
5     AA+
6     AA+
7       C
8     AA+
9       C
10    AA+
11    NaN
12    AA+
13      C
14    AA+
Name: Grade, dtype: category
Categories (2, object): ['C' < 'AA+']

In [49]:
df ['Fees'] = df['Fees_Paid'].where(df['Fees_Paid'] < 15000, 1000)
df["Fees"]

0      1000
1      1000
2      1000
3      1000
4      1000
5      1000
6     12000
7      1000
8      1000
9      1000
10    12000
11     1000
12     1000
13     1000
14     1000
Name: Fees, dtype: int64

In [52]:
df ['Fees2'] = df['Fees_Paid'].mask(df['Fees_Paid'] < 15000, 1000)
df ['Fees2']

0     15000
1     18000
2     15000
3     20000
4     18000
5     15000
6      1000
7     20000
8     15000
9     18000
10     1000
11    15000
12    20000
13    18000
14    15000
Name: Fees2, dtype: int64

In [ ]:
df.groupby('Student_name')['']