In [9]:
import pandas as pd 
df = pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [10]:
df.shape

(100, 6)

In [11]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [13]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [14]:
df.describe(include = 'object')

        gender cough     city has_covid
count      100   100      100       100
unique       2     2        4         2
top     Female  Mild  Kolkata        No
freq        59    62       32        55

In [15]:
df.values

array([[60, 'Male', 103.0, 'Mild', 'Kolkata', 'No'],
       [27, 'Male', 100.0, 'Mild', 'Delhi', 'Yes'],
       [42, 'Male', 101.0, 'Mild', 'Delhi', 'No'],
       [31, 'Female', 98.0, 'Mild', 'Kolkata', 'No'],
       [65, 'Female', 101.0, 'Mild', 'Mumbai', 'No'],
       [84, 'Female', nan, 'Mild', 'Bangalore', 'Yes'],
       [14, 'Male', 101.0, 'Strong', 'Bangalore', 'No'],
       [20, 'Female', nan, 'Strong', 'Mumbai', 'Yes'],
       [19, 'Female', 100.0, 'Strong', 'Bangalore', 'No'],
       [64, 'Female', 101.0, 'Mild', 'Delhi', 'No'],
       [75, 'Female', nan, 'Mild', 'Delhi', 'No'],
       [65, 'Female', 98.0, 'Mild', 'Mumbai', 'Yes'],
       [25, 'Female', 99.0, 'Strong', 'Kolkata', 'No'],
       [64, 'Male', 102.0, 'Mild', 'Bangalore', 'Yes'],
       [51, 'Male', 104.0, 'Mild', 'Bangalore', 'No'],
       [70, 'Male', 103.0, 'Strong', 'Kolkata', 'Yes'],
       [69, 'Female', 103.0, 'Mild', 'Kolkata', 'Yes'],
       [40, 'Female', 98.0, 'Strong', 'Delhi', 'No'],
       [64, 'Female', 98.0, 'Mild', 'Bangalore', 'Yes'],
       [42, 'Female', nan, 'Strong', 'Bangalore', 'Yes'],
       [12, 'Male', 98.0, 'Strong', 'Bangalore', 'No'],
       [73, 'Male', 98.0, 'Mild', 'Bangalore', 'Yes'],
       [71, 'Female', 98.0, 'Strong', 'Kolkata', 'Yes'],
       [80, 'Female', 98.0, 'Mild', 'Delhi', 'Yes'],
       [13, 'Female', 100.0, 'Strong', 'Kolkata', 'No'],
       [23, 'Male', nan, 'Mild', 'Mumbai', 'No'],
       [19, 'Female', 100.0, 'Mild', 'Kolkata', 'Yes'],
       [33, 'Female', 102.0, 'Strong', 'Delhi', 'No'],
       [16, 'Male', 104.0, 'Mild', 'Kolkata', 'No'],
       [34, 'Female', nan, 'Strong', 'Mumbai', 'Yes'],
       [15, 'Male', 101.0, 'Mild', 'Delhi', 'Yes'],
       [83, 'Male', 103.0, 'Mild', 'Kolkata', 'No'],
       [34, 'Female', 101.0, 'Strong', 'Delhi', 'Yes'],
       [26, 'Female', 98.0, 'Mild', 'Kolkata', 'No'],
       [74, 'Male', 102.0, 'Mild', 'Mumbai', 'Yes'],
       [82, 'Female', 102.0, 'Strong', 'Bangalore', 'No'],
       [38, 'Female', 101.0, 'Mild', 'Bangalore', 'No'],
       [55, 'Male', 100.0, 'Mild', 'Kolkata', 'No'],
       [49, 'Female', 101.0, 'Mild', 'Delhi', 'Yes'],
       [50, 'Female', 103.0, 'Mild', 'Kolkata', 'No'],
       [49, 'Female', 102.0, 'Mild', 'Delhi', 'No'],
       [82, 'Male', nan, 'Mild', 'Kolkata', 'Yes'],
       [27, 'Male', 100.0, 'Mild', 'Delhi', 'Yes'],
       [22, 'Female', 99.0, 'Mild', 'Bangalore', 'Yes'],
       [20, 'Male', 102.0, 'Strong', 'Delhi', 'No'],
       [72, 'Male', 99.0, 'Mild', 'Bangalore', 'No'],
       [19, 'Female', 101.0, 'Mild', 'Mumbai', 'No'],
       [18, 'Female', 104.0, 'Mild', 'Bangalore', 'No'],
       [66, 'Male', 99.0, 'Strong', 'Bangalore', 'No'],
       [44, 'Male', 104.0, 'Mild', 'Mumbai', 'No'],
       [19, 'Male', 101.0, 'Mild', 'Delhi', 'Yes'],
       [11, 'Female', 100.0, 'Strong', 'Kolkata', 'Yes'],
       [47, 'Female', 100.0, 'Strong', 'Bangalore', 'Yes'],
       [83, 'Male', 98.0, 'Mild', 'Delhi', 'Yes'],
       [60, 'Female', 99.0, 'Mild', 'Mumbai', 'Yes'],
       [81, 'Female', 101.0, 'Mild', 'Mumbai', 'Yes'],
       [71, 'Male', nan, 'Strong', 'Kolkata', 'No'],
       [49, 'Female', 99.0, 'Strong', 'Bangalore', 'No'],
       [23, 'Male', 98.0, 'Strong', 'Mumbai', 'Yes'],
       [6, 'Female', 104.0, 'Mild', 'Kolkata', 'Yes'],
       [24, 'Female', 102.0, 'Strong', 'Bangalore', 'Yes'],
       [81, 'Female', 98.0, 'Strong', 'Mumbai', 'No'],
       [56, 'Female', 104.0, 'Strong', 'Bangalore', 'Yes'],
       [10, 'Male', 100.0, 'Mild', 'Bangalore', 'No'],
       [42, 'Male', 104.0, 'Mild', 'Mumbai', 'No'],
       [69, 'Female', 102.0, 'Mild', 'Bangalore', 'No'],
       [51, 'Male', 104.0, 'Mild', 'Kolkata', 'No'],
       [65, 'Male', 99.0, 'Mild', 'Bangalore', 'No'],
       [54, 'Female', 104.0, 'Strong', 'Kolkata', 'No'],
       [73, 'Female', 103.0, 'Mild', 'Delhi', 'No'],
       [68, 'Female', 101.0, 'Strong', 'Delhi', 'No'],
       [75, 'Female', 104.0, 'Strong', 'Delhi', 'No'],
       [83, 'Female', 101.0, 'Mild', 'Kolkata', 'No'],
       [34, 'Male', 98.0, 'Strong', 'Kolkata', 'Yes'],
       [34, 'Female', 104.0, 'Strong', 'Delhi', 'No'],
       [5, 'Male', 102.0, 'Mild', 'Kolkata', 'Yes'],
       [80, 'Male', 100.0, 'Mild', 'Bangalore', 'Yes'],
       [8, 'Female', 101.0, 'Mild', 'Kolkata', 'No'],
       [11, 'Male', 100.0, 'Mild', 'Bangalore', 'Yes'],
       [48, 'Female', 103.0, 'Mild', 'Kolkata', 'Yes'],
       [14, 'Female', 99.0, 'Mild', 'Mumbai', 'Yes'],
       [65, 'Male', 99.0, 'Mild', 'Delhi', 'No'],
       [24, 'Male', 98.0, 'Mild', 'Kolkata', 'Yes'],
       [17, 'Female', 104.0, 'Mild', 'Kolkata', 'No'],
       [69, 'Female', 98.0, 'Strong', 'Mumbai', 'No'],
       [16, 'Female', 103.0, 'Mild', 'Bangalore', 'Yes'],
       [25, 'Male', 104.0, 'Mild', 'Bangalore', 'Yes'],
       [47, 'Male', 101.0, 'Strong', 'Bangalore', 'No'],
       [5, 'Female', 100.0, 'Mild', 'Kolkata', 'No'],
       [46, 'Male', 103.0, 'Strong', 'Bangalore', 'No'],
       [59, 'Female', 99.0, 'Strong', 'Delhi', 'No'],
       [38, 'Male', nan, 'Mild', 'Delhi', 'Yes'],
       [82, 'Female', 102.0, 'Strong', 'Kolkata', 'No'],
       [27, 'Male', 100.0, 'Mild', 'Kolkata', 'Yes'],
       [79, 'Male', nan, 'Strong', 'Kolkata', 'Yes'],
       [12, 'Female', 104.0, 'Mild', 'Bangalore', 'No'],
       [51, 'Female', 101.0, 'Strong', 'Kolkata', 'Yes'],
       [20, 'Female', 101.0, 'Mild', 'Bangalore', 'No'],
       [5, 'Female', 98.0, 'Strong', 'Mumbai', 'No'],
       [10, 'Female', 98.0, 'Strong', 'Kolkata', 'Yes']], dtype=object)

In [16]:
df["age"]

0     60
1     27
2     42
3     31
4     65
      ..
95    12
96    51
97    20
98     5
99    10
Name: age, Length: 100, dtype: int64

In [17]:
df[['age', 'fever']]

    age  fever
0    60  103.0
1    27  100.0
2    42  101.0
3    31   98.0
4    65  101.0
..  ...    ...
95   12  104.0
96   51  101.0
97   20  101.0
98    5   98.0
99   10   98.0

[100 rows x 2 columns]

In [18]:
df.index = range (50, 150)
df.head()

    age  gender  fever cough     city has_covid
50   60    Male  103.0  Mild  Kolkata        No
51   27    Male  100.0  Mild    Delhi       Yes
52   42    Male  101.0  Mild    Delhi        No
53   31  Female   98.0  Mild  Kolkata        No
54   65  Female  101.0  Mild   Mumbai        No

In [19]:
# df.loc[108]         # acc. to row lable 
df.loc [108: 123]     # slicing me last value jo hai vo included rahti hai

     age  gender  fever   cough       city has_covid
108   23    Male   98.0  Strong     Mumbai       Yes
109    6  Female  104.0    Mild    Kolkata       Yes
110   24  Female  102.0  Strong  Bangalore       Yes
111   81  Female   98.0  Strong     Mumbai        No
112   56  Female  104.0  Strong  Bangalore       Yes
113   10    Male  100.0    Mild  Bangalore        No
114   42    Male  104.0    Mild     Mumbai        No
115   69  Female  102.0    Mild  Bangalore        No
116   51    Male  104.0    Mild    Kolkata        No
117   65    Male   99.0    Mild  Bangalore        No
118   54  Female  104.0  Strong    Kolkata        No
119   73  Female  103.0    Mild      Delhi        No
120   68  Female  101.0  Strong      Delhi        No
121   75  Female  104.0  Strong      Delhi        No
122   83  Female  101.0    Mild    Kolkata        No
123   34    Male   98.0  Strong    Kolkata       Yes

In [20]:
# df.iloc[8]           # position and index ke basis per karta hai 
df.iloc[8: 13]        # isme last wala include nahi rahta

    age  gender  fever   cough       city has_covid
58   19  Female  100.0  Strong  Bangalore        No
59   64  Female  101.0    Mild      Delhi        No
60   75  Female    NaN    Mild      Delhi        No
61   65  Female   98.0    Mild     Mumbai       Yes
62   25  Female   99.0  Strong    Kolkata        No

In [21]:
df['age']

50     60
51     27
52     42
53     31
54     65
       ..
145    12
146    51
147    20
148     5
149    10
Name: age, Length: 100, dtype: int64

In [22]:
df[['age', 'fever']]

     age  fever
50    60  103.0
51    27  100.0
52    42  101.0
53    31   98.0
54    65  101.0
..   ...    ...
145   12  104.0
146   51  101.0
147   20  101.0
148    5   98.0
149   10   98.0

[100 rows x 2 columns]

In [23]:
df [df ['age'] > 50]

     age  gender  fever   cough       city has_covid
50    60    Male  103.0    Mild    Kolkata        No
54    65  Female  101.0    Mild     Mumbai        No
55    84  Female    NaN    Mild  Bangalore       Yes
59    64  Female  101.0    Mild      Delhi        No
60    75  Female    NaN    Mild      Delhi        No
61    65  Female   98.0    Mild     Mumbai       Yes
63    64    Male  102.0    Mild  Bangalore       Yes
64    51    Male  104.0    Mild  Bangalore        No
65    70    Male  103.0  Strong    Kolkata       Yes
66    69  Female  103.0    Mild    Kolkata       Yes
68    64  Female   98.0    Mild  Bangalore       Yes
71    73    Male   98.0    Mild  Bangalore       Yes
72    71  Female   98.0  Strong    Kolkata       Yes
73    80  Female   98.0    Mild      Delhi       Yes
81    83    Male  103.0    Mild    Kolkata        No
84    74    Male  102.0    Mild     Mumbai       Yes
85    82  Female  102.0  Strong  Bangalore        No
87    55    Male  100.0    Mild    Kolkata        No
91    82    Male    NaN    Mild    Kolkata       Yes
95    72    Male   99.0    Mild  Bangalore        No
98    66    Male   99.0  Strong  Bangalore        No
103   83    Male   98.0    Mild      Delhi       Yes
104   60  Female   99.0    Mild     Mumbai       Yes
105   81  Female  101.0    Mild     Mumbai       Yes
106   71    Male    NaN  Strong    Kolkata        No
111   81  Female   98.0  Strong     Mumbai        No
112   56  Female  104.0  Strong  Bangalore       Yes
115   69  Female  102.0    Mild  Bangalore        No
116   51    Male  104.0    Mild    Kolkata        No
117   65    Male   99.0    Mild  Bangalore        No
118   54  Female  104.0  Strong    Kolkata        No
119   73  Female  103.0    Mild      Delhi        No
120   68  Female  101.0  Strong      Delhi        No
121   75  Female  104.0  Strong      Delhi        No
122   83  Female  101.0    Mild    Kolkata        No
126   80    Male  100.0    Mild  Bangalore       Yes
131   65    Male   99.0    Mild      Delhi        No
134   69  Female   98.0  Strong     Mumbai        No
140   59  Female   99.0  Strong      Delhi        No
142   82  Female  102.0  Strong    Kolkata        No
144   79    Male    NaN  Strong    Kolkata       Yes
146   51  Female  101.0  Strong    Kolkata       Yes

In [24]:
df[df['age'] < 30]

     age  gender  fever   cough       city has_covid
51    27    Male  100.0    Mild      Delhi       Yes
56    14    Male  101.0  Strong  Bangalore        No
57    20  Female    NaN  Strong     Mumbai       Yes
58    19  Female  100.0  Strong  Bangalore        No
62    25  Female   99.0  Strong    Kolkata        No
70    12    Male   98.0  Strong  Bangalore        No
74    13  Female  100.0  Strong    Kolkata        No
75    23    Male    NaN    Mild     Mumbai        No
76    19  Female  100.0    Mild    Kolkata       Yes
78    16    Male  104.0    Mild    Kolkata        No
80    15    Male  101.0    Mild      Delhi       Yes
83    26  Female   98.0    Mild    Kolkata        No
92    27    Male  100.0    Mild      Delhi       Yes
93    22  Female   99.0    Mild  Bangalore       Yes
94    20    Male  102.0  Strong      Delhi        No
96    19  Female  101.0    Mild     Mumbai        No
97    18  Female  104.0    Mild  Bangalore        No
100   19    Male  101.0    Mild      Delhi       Yes
101   11  Female  100.0  Strong    Kolkata       Yes
108   23    Male   98.0  Strong     Mumbai       Yes
109    6  Female  104.0    Mild    Kolkata       Yes
110   24  Female  102.0  Strong  Bangalore       Yes
113   10    Male  100.0    Mild  Bangalore        No
125    5    Male  102.0    Mild    Kolkata       Yes
127    8  Female  101.0    Mild    Kolkata        No
128   11    Male  100.0    Mild  Bangalore       Yes
130   14  Female   99.0    Mild     Mumbai       Yes
132   24    Male   98.0    Mild    Kolkata       Yes
133   17  Female  104.0    Mild    Kolkata        No
135   16  Female  103.0    Mild  Bangalore       Yes
136   25    Male  104.0    Mild  Bangalore       Yes
138    5  Female  100.0    Mild    Kolkata        No
143   27    Male  100.0    Mild    Kolkata       Yes
145   12  Female  104.0    Mild  Bangalore        No
147   20  Female  101.0    Mild  Bangalore        No
148    5  Female   98.0  Strong     Mumbai        No
149   10  Female   98.0  Strong    Kolkata       Yes

In [25]:
df [df ['fever'] > 100]

     age  gender  fever   cough       city has_covid
50    60    Male  103.0    Mild    Kolkata        No
52    42    Male  101.0    Mild      Delhi        No
54    65  Female  101.0    Mild     Mumbai        No
56    14    Male  101.0  Strong  Bangalore        No
59    64  Female  101.0    Mild      Delhi        No
63    64    Male  102.0    Mild  Bangalore       Yes
64    51    Male  104.0    Mild  Bangalore        No
65    70    Male  103.0  Strong    Kolkata       Yes
66    69  Female  103.0    Mild    Kolkata       Yes
77    33  Female  102.0  Strong      Delhi        No
78    16    Male  104.0    Mild    Kolkata        No
80    15    Male  101.0    Mild      Delhi       Yes
81    83    Male  103.0    Mild    Kolkata        No
82    34  Female  101.0  Strong      Delhi       Yes
84    74    Male  102.0    Mild     Mumbai       Yes
85    82  Female  102.0  Strong  Bangalore        No
86    38  Female  101.0    Mild  Bangalore        No
88    49  Female  101.0    Mild      Delhi       Yes
89    50  Female  103.0    Mild    Kolkata        No
90    49  Female  102.0    Mild      Delhi        No
94    20    Male  102.0  Strong      Delhi        No
96    19  Female  101.0    Mild     Mumbai        No
97    18  Female  104.0    Mild  Bangalore        No
99    44    Male  104.0    Mild     Mumbai        No
100   19    Male  101.0    Mild      Delhi       Yes
105   81  Female  101.0    Mild     Mumbai       Yes
109    6  Female  104.0    Mild    Kolkata       Yes
110   24  Female  102.0  Strong  Bangalore       Yes
112   56  Female  104.0  Strong  Bangalore       Yes
114   42    Male  104.0    Mild     Mumbai        No
115   69  Female  102.0    Mild  Bangalore        No
116   51    Male  104.0    Mild    Kolkata        No
118   54  Female  104.0  Strong    Kolkata        No
119   73  Female  103.0    Mild      Delhi        No
120   68  Female  101.0  Strong      Delhi        No
121   75  Female  104.0  Strong      Delhi        No
122   83  Female  101.0    Mild    Kolkata        No
124   34  Female  104.0  Strong      Delhi        No
125    5    Male  102.0    Mild    Kolkata       Yes
127    8  Female  101.0    Mild    Kolkata        No
129   48  Female  103.0    Mild    Kolkata       Yes
133   17  Female  104.0    Mild    Kolkata        No
135   16  Female  103.0    Mild  Bangalore       Yes
136   25    Male  104.0    Mild  Bangalore       Yes
137   47    Male  101.0  Strong  Bangalore        No
139   46    Male  103.0  Strong  Bangalore        No
142   82  Female  102.0  Strong    Kolkata        No
145   12  Female  104.0    Mild  Bangalore        No
146   51  Female  101.0  Strong    Kolkata       Yes
147   20  Female  101.0    Mild  Bangalore        No

In [26]:
df [ df ['gender'] == 'Female']

     age  gender  fever   cough       city has_covid
53    31  Female   98.0    Mild    Kolkata        No
54    65  Female  101.0    Mild     Mumbai        No
55    84  Female    NaN    Mild  Bangalore       Yes
57    20  Female    NaN  Strong     Mumbai       Yes
58    19  Female  100.0  Strong  Bangalore        No
59    64  Female  101.0    Mild      Delhi        No
60    75  Female    NaN    Mild      Delhi        No
61    65  Female   98.0    Mild     Mumbai       Yes
62    25  Female   99.0  Strong    Kolkata        No
66    69  Female  103.0    Mild    Kolkata       Yes
67    40  Female   98.0  Strong      Delhi        No
68    64  Female   98.0    Mild  Bangalore       Yes
69    42  Female    NaN  Strong  Bangalore       Yes
72    71  Female   98.0  Strong    Kolkata       Yes
73    80  Female   98.0    Mild      Delhi       Yes
74    13  Female  100.0  Strong    Kolkata        No
76    19  Female  100.0    Mild    Kolkata       Yes
77    33  Female  102.0  Strong      Delhi        No
79    34  Female    NaN  Strong     Mumbai       Yes
82    34  Female  101.0  Strong      Delhi       Yes
83    26  Female   98.0    Mild    Kolkata        No
85    82  Female  102.0  Strong  Bangalore        No
86    38  Female  101.0    Mild  Bangalore        No
88    49  Female  101.0    Mild      Delhi       Yes
89    50  Female  103.0    Mild    Kolkata        No
90    49  Female  102.0    Mild      Delhi        No
93    22  Female   99.0    Mild  Bangalore       Yes
96    19  Female  101.0    Mild     Mumbai        No
97    18  Female  104.0    Mild  Bangalore        No
101   11  Female  100.0  Strong    Kolkata       Yes
102   47  Female  100.0  Strong  Bangalore       Yes
104   60  Female   99.0    Mild     Mumbai       Yes
105   81  Female  101.0    Mild     Mumbai       Yes
107   49  Female   99.0  Strong  Bangalore        No
109    6  Female  104.0    Mild    Kolkata       Yes
110   24  Female  102.0  Strong  Bangalore       Yes
111   81  Female   98.0  Strong     Mumbai        No
112   56  Female  104.0  Strong  Bangalore       Yes
115   69  Female  102.0    Mild  Bangalore        No
118   54  Female  104.0  Strong    Kolkata        No
119   73  Female  103.0    Mild      Delhi        No
120   68  Female  101.0  Strong      Delhi        No
121   75  Female  104.0  Strong      Delhi        No
122   83  Female  101.0    Mild    Kolkata        No
124   34  Female  104.0  Strong      Delhi        No
127    8  Female  101.0    Mild    Kolkata        No
129   48  Female  103.0    Mild    Kolkata       Yes
130   14  Female   99.0    Mild     Mumbai       Yes
133   17  Female  104.0    Mild    Kolkata        No
134   69  Female   98.0  Strong     Mumbai        No
135   16  Female  103.0    Mild  Bangalore       Yes
138    5  Female  100.0    Mild    Kolkata        No
140   59  Female   99.0  Strong      Delhi        No
142   82  Female  102.0  Strong    Kolkata        No
145   12  Female  104.0    Mild  Bangalore        No
146   51  Female  101.0  Strong    Kolkata       Yes
147   20  Female  101.0    Mild  Bangalore        No
148    5  Female   98.0  Strong     Mumbai        No
149   10  Female   98.0  Strong    Kolkata       Yes

In [27]:
df[ df['city'] == 'Delhi']

     age  gender  fever   cough   city has_covid
51    27    Male  100.0    Mild  Delhi       Yes
52    42    Male  101.0    Mild  Delhi        No
59    64  Female  101.0    Mild  Delhi        No
60    75  Female    NaN    Mild  Delhi        No
67    40  Female   98.0  Strong  Delhi        No
73    80  Female   98.0    Mild  Delhi       Yes
77    33  Female  102.0  Strong  Delhi        No
80    15    Male  101.0    Mild  Delhi       Yes
82    34  Female  101.0  Strong  Delhi       Yes
88    49  Female  101.0    Mild  Delhi       Yes
90    49  Female  102.0    Mild  Delhi        No
92    27    Male  100.0    Mild  Delhi       Yes
94    20    Male  102.0  Strong  Delhi        No
100   19    Male  101.0    Mild  Delhi       Yes
103   83    Male   98.0    Mild  Delhi       Yes
119   73  Female  103.0    Mild  Delhi        No
120   68  Female  101.0  Strong  Delhi        No
121   75  Female  104.0  Strong  Delhi        No
124   34  Female  104.0  Strong  Delhi        No
131   65    Male   99.0    Mild  Delhi        No
140   59  Female   99.0  Strong  Delhi        No
141   38    Male    NaN    Mild  Delhi       Yes

In [28]:
df [ df ['has_covid'] == 'No']

     age  gender  fever   cough       city has_covid
50    60    Male  103.0    Mild    Kolkata        No
52    42    Male  101.0    Mild      Delhi        No
53    31  Female   98.0    Mild    Kolkata        No
54    65  Female  101.0    Mild     Mumbai        No
56    14    Male  101.0  Strong  Bangalore        No
58    19  Female  100.0  Strong  Bangalore        No
59    64  Female  101.0    Mild      Delhi        No
60    75  Female    NaN    Mild      Delhi        No
62    25  Female   99.0  Strong    Kolkata        No
64    51    Male  104.0    Mild  Bangalore        No
67    40  Female   98.0  Strong      Delhi        No
70    12    Male   98.0  Strong  Bangalore        No
74    13  Female  100.0  Strong    Kolkata        No
75    23    Male    NaN    Mild     Mumbai        No
77    33  Female  102.0  Strong      Delhi        No
78    16    Male  104.0    Mild    Kolkata        No
81    83    Male  103.0    Mild    Kolkata        No
83    26  Female   98.0    Mild    Kolkata        No
85    82  Female  102.0  Strong  Bangalore        No
86    38  Female  101.0    Mild  Bangalore        No
87    55    Male  100.0    Mild    Kolkata        No
89    50  Female  103.0    Mild    Kolkata        No
90    49  Female  102.0    Mild      Delhi        No
94    20    Male  102.0  Strong      Delhi        No
95    72    Male   99.0    Mild  Bangalore        No
96    19  Female  101.0    Mild     Mumbai        No
97    18  Female  104.0    Mild  Bangalore        No
98    66    Male   99.0  Strong  Bangalore        No
99    44    Male  104.0    Mild     Mumbai        No
106   71    Male    NaN  Strong    Kolkata        No
107   49  Female   99.0  Strong  Bangalore        No
111   81  Female   98.0  Strong     Mumbai        No
113   10    Male  100.0    Mild  Bangalore        No
114   42    Male  104.0    Mild     Mumbai        No
115   69  Female  102.0    Mild  Bangalore        No
116   51    Male  104.0    Mild    Kolkata        No
117   65    Male   99.0    Mild  Bangalore        No
118   54  Female  104.0  Strong    Kolkata        No
119   73  Female  103.0    Mild      Delhi        No
120   68  Female  101.0  Strong      Delhi        No
121   75  Female  104.0  Strong      Delhi        No
122   83  Female  101.0    Mild    Kolkata        No
124   34  Female  104.0  Strong      Delhi        No
127    8  Female  101.0    Mild    Kolkata        No
131   65    Male   99.0    Mild      Delhi        No
133   17  Female  104.0    Mild    Kolkata        No
134   69  Female   98.0  Strong     Mumbai        No
137   47    Male  101.0  Strong  Bangalore        No
138    5  Female  100.0    Mild    Kolkata        No
139   46    Male  103.0  Strong  Bangalore        No
140   59  Female   99.0  Strong      Delhi        No
142   82  Female  102.0  Strong    Kolkata        No
145   12  Female  104.0    Mild  Bangalore        No
147   20  Female  101.0    Mild  Bangalore        No
148    5  Female   98.0  Strong     Mumbai        No

In [29]:
df[(df['age'] > 40) & (df ['has_covid'] == 'Yes')]

     age  gender  fever   cough       city has_covid
55    84  Female    NaN    Mild  Bangalore       Yes
61    65  Female   98.0    Mild     Mumbai       Yes
63    64    Male  102.0    Mild  Bangalore       Yes
65    70    Male  103.0  Strong    Kolkata       Yes
66    69  Female  103.0    Mild    Kolkata       Yes
68    64  Female   98.0    Mild  Bangalore       Yes
69    42  Female    NaN  Strong  Bangalore       Yes
71    73    Male   98.0    Mild  Bangalore       Yes
72    71  Female   98.0  Strong    Kolkata       Yes
73    80  Female   98.0    Mild      Delhi       Yes
84    74    Male  102.0    Mild     Mumbai       Yes
88    49  Female  101.0    Mild      Delhi       Yes
91    82    Male    NaN    Mild    Kolkata       Yes
102   47  Female  100.0  Strong  Bangalore       Yes
103   83    Male   98.0    Mild      Delhi       Yes
104   60  Female   99.0    Mild     Mumbai       Yes
105   81  Female  101.0    Mild     Mumbai       Yes
112   56  Female  104.0  Strong  Bangalore       Yes
126   80    Male  100.0    Mild  Bangalore       Yes
129   48  Female  103.0    Mild    Kolkata       Yes
144   79    Male    NaN  Strong    Kolkata       Yes
146   51  Female  101.0  Strong    Kolkata       Yes

In [30]:
df.query('age > 40 and has_covid == "Yes"')

     age  gender  fever   cough       city has_covid
55    84  Female    NaN    Mild  Bangalore       Yes
61    65  Female   98.0    Mild     Mumbai       Yes
63    64    Male  102.0    Mild  Bangalore       Yes
65    70    Male  103.0  Strong    Kolkata       Yes
66    69  Female  103.0    Mild    Kolkata       Yes
68    64  Female   98.0    Mild  Bangalore       Yes
69    42  Female    NaN  Strong  Bangalore       Yes
71    73    Male   98.0    Mild  Bangalore       Yes
72    71  Female   98.0  Strong    Kolkata       Yes
73    80  Female   98.0    Mild      Delhi       Yes
84    74    Male  102.0    Mild     Mumbai       Yes
88    49  Female  101.0    Mild      Delhi       Yes
91    82    Male    NaN    Mild    Kolkata       Yes
102   47  Female  100.0  Strong  Bangalore       Yes
103   83    Male   98.0    Mild      Delhi       Yes
104   60  Female   99.0    Mild     Mumbai       Yes
105   81  Female  101.0    Mild     Mumbai       Yes
112   56  Female  104.0  Strong  Bangalore       Yes
126   80    Male  100.0    Mild  Bangalore       Yes
129   48  Female  103.0    Mild    Kolkata       Yes
144   79    Male    NaN  Strong    Kolkata       Yes
146   51  Female  101.0  Strong    Kolkata       Yes

In [36]:
df[(df['fever'] > 98.0) & (df ['city'] == 'Mumbai')]

     age  gender  fever cough    city has_covid
54    65  Female  101.0  Mild  Mumbai        No
84    74    Male  102.0  Mild  Mumbai       Yes
96    19  Female  101.0  Mild  Mumbai        No
99    44    Male  104.0  Mild  Mumbai        No
104   60  Female   99.0  Mild  Mumbai       Yes
105   81  Female  101.0  Mild  Mumbai       Yes
114   42    Male  104.0  Mild  Mumbai        No
130   14  Female   99.0  Mild  Mumbai       Yes

In [40]:
df.sort_values(['age'], ascending = False)

     age  gender  fever   cough       city has_covid
55    84  Female    NaN    Mild  Bangalore       Yes
122   83  Female  101.0    Mild    Kolkata        No
81    83    Male  103.0    Mild    Kolkata        No
103   83    Male   98.0    Mild      Delhi       Yes
85    82  Female  102.0  Strong  Bangalore        No
..   ...     ...    ...     ...        ...       ...
127    8  Female  101.0    Mild    Kolkata        No
109    6  Female  104.0    Mild    Kolkata       Yes
138    5  Female  100.0    Mild    Kolkata        No
125    5    Male  102.0    Mild    Kolkata       Yes
148    5  Female   98.0  Strong     Mumbai        No

[100 rows x 6 columns]

In [42]:
df.sort_values (['age', 'fever'], ascending = [False, True])

     age  gender  fever   cough       city has_covid
55    84  Female    NaN    Mild  Bangalore       Yes
103   83    Male   98.0    Mild      Delhi       Yes
122   83  Female  101.0    Mild    Kolkata        No
81    83    Male  103.0    Mild    Kolkata        No
85    82  Female  102.0  Strong  Bangalore        No
..   ...     ...    ...     ...        ...       ...
127    8  Female  101.0    Mild    Kolkata        No
109    6  Female  104.0    Mild    Kolkata       Yes
148    5  Female   98.0  Strong     Mumbai        No
138    5  Female  100.0    Mild    Kolkata        No
125    5    Male  102.0    Mild    Kolkata       Yes

[100 rows x 6 columns]

In [44]:
df.nlargest(5, 'age')

     age  gender  fever   cough       city has_covid
55    84  Female    NaN    Mild  Bangalore       Yes
81    83    Male  103.0    Mild    Kolkata        No
103   83    Male   98.0    Mild      Delhi       Yes
122   83  Female  101.0    Mild    Kolkata        No
85    82  Female  102.0  Strong  Bangalore        No

In [46]:
df.nsmallest(6, 'fever')

    age  gender  fever   cough       city has_covid
53   31  Female   98.0    Mild    Kolkata        No
61   65  Female   98.0    Mild     Mumbai       Yes
67   40  Female   98.0  Strong      Delhi        No
68   64  Female   98.0    Mild  Bangalore       Yes
70   12    Male   98.0  Strong  Bangalore        No
71   73    Male   98.0    Mild  Bangalore       Yes

In [53]:
df['age_Rank'] = df ['age'].rank(ascending = False, method = 'dense')
df

     age  gender  fever   cough       city has_covid  age_Rank
50    60    Male  103.0    Mild    Kolkata        No      18.0
51    27    Male  100.0    Mild      Delhi       Yes      36.0
52    42    Male  101.0    Mild      Delhi        No      30.0
53    31  Female   98.0    Mild    Kolkata        No      35.0
54    65  Female  101.0    Mild     Mumbai        No      16.0
..   ...     ...    ...     ...        ...       ...       ...
145   12  Female  104.0    Mild  Bangalore        No      50.0
146   51  Female  101.0  Strong    Kolkata       Yes      23.0
147   20  Female  101.0    Mild  Bangalore        No      42.0
148    5  Female   98.0  Strong     Mumbai        No      55.0
149   10  Female   98.0  Strong    Kolkata       Yes      52.0

[100 rows x 7 columns]

In [55]:
df.isna()
df.isnull()

# df.isna().sum()
# df.isna().sum().sum()

       age  gender  fever  cough   city  has_covid  age_Rank
50   False   False  False  False  False      False     False
51   False   False  False  False  False      False     False
52   False   False  False  False  False      False     False
53   False   False  False  False  False      False     False
54   False   False  False  False  False      False     False
..     ...     ...    ...    ...    ...        ...       ...
145  False   False  False  False  False      False     False
146  False   False  False  False  False      False     False
147  False   False  False  False  False      False     False
148  False   False  False  False  False      False     False
149  False   False  False  False  False      False     False

[100 rows x 7 columns]

In [57]:
df.dropna()

     age  gender  fever   cough       city has_covid  age_Rank
50    60    Male  103.0    Mild    Kolkata        No      18.0
51    27    Male  100.0    Mild      Delhi       Yes      36.0
52    42    Male  101.0    Mild      Delhi        No      30.0
53    31  Female   98.0    Mild    Kolkata        No      35.0
54    65  Female  101.0    Mild     Mumbai        No      16.0
..   ...     ...    ...     ...        ...       ...       ...
145   12  Female  104.0    Mild  Bangalore        No      50.0
146   51  Female  101.0  Strong    Kolkata       Yes      23.0
147   20  Female  101.0    Mild  Bangalore        No      42.0
148    5  Female   98.0  Strong     Mumbai        No      55.0
149   10  Female   98.0  Strong    Kolkata       Yes      52.0

[90 rows x 7 columns]

In [59]:
df.fillna (0)

     age  gender  fever   cough       city has_covid  age_Rank
50    60    Male  103.0    Mild    Kolkata        No      18.0
51    27    Male  100.0    Mild      Delhi       Yes      36.0
52    42    Male  101.0    Mild      Delhi        No      30.0
53    31  Female   98.0    Mild    Kolkata        No      35.0
54    65  Female  101.0    Mild     Mumbai        No      16.0
..   ...     ...    ...     ...        ...       ...       ...
145   12  Female  104.0    Mild  Bangalore        No      50.0
146   51  Female  101.0  Strong    Kolkata       Yes      23.0
147   20  Female  101.0    Mild  Bangalore        No      42.0
148    5  Female   98.0  Strong     Mumbai        No      55.0
149   10  Female   98.0  Strong    Kolkata       Yes      52.0

[100 rows x 7 columns]

In [62]:
df['age'].fillna (df['age'].mean())

50     60
51     27
52     42
53     31
54     65
       ..
145    12
146    51
147    20
148     5
149    10
Name: age, Length: 100, dtype: int64

In [65]:
df.duplicated()

50     False
51     False
52     False
53     False
54     False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 100, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(1)

In [69]:
df.drop_duplicates()

     age  gender  fever   cough       city has_covid  age_Rank
50    60    Male  103.0    Mild    Kolkata        No      18.0
51    27    Male  100.0    Mild      Delhi       Yes      36.0
52    42    Male  101.0    Mild      Delhi        No      30.0
53    31  Female   98.0    Mild    Kolkata        No      35.0
54    65  Female  101.0    Mild     Mumbai        No      16.0
..   ...     ...    ...     ...        ...       ...       ...
145   12  Female  104.0    Mild  Bangalore        No      50.0
146   51  Female  101.0  Strong    Kolkata       Yes      23.0
147   20  Female  101.0    Mild  Bangalore        No      42.0
148    5  Female   98.0  Strong     Mumbai        No      55.0
149   10  Female   98.0  Strong    Kolkata       Yes      52.0

[99 rows x 7 columns]

In [70]:
df.drop_duplicates(subset = ['age'])

     age  gender  fever   cough       city has_covid  age_Rank
50    60    Male  103.0    Mild    Kolkata        No      18.0
51    27    Male  100.0    Mild      Delhi       Yes      36.0
52    42    Male  101.0    Mild      Delhi        No      30.0
53    31  Female   98.0    Mild    Kolkata        No      35.0
54    65  Female  101.0    Mild     Mumbai        No      16.0
55    84  Female    NaN    Mild  Bangalore       Yes       1.0
56    14    Male  101.0  Strong  Bangalore        No      48.0
57    20  Female    NaN  Strong     Mumbai       Yes      42.0
58    19  Female  100.0  Strong  Bangalore        No      43.0
59    64  Female  101.0    Mild      Delhi        No      17.0
60    75  Female    NaN    Mild      Delhi        No       7.0
62    25  Female   99.0  Strong    Kolkata        No      38.0
64    51    Male  104.0    Mild  Bangalore        No      23.0
65    70    Male  103.0  Strong    Kolkata       Yes      12.0
66    69  Female  103.0    Mild    Kolkata       Yes      13.0
67    40  Female   98.0  Strong      Delhi        No      31.0
70    12    Male   98.0  Strong  Bangalore        No      50.0
71    73    Male   98.0    Mild  Bangalore       Yes       9.0
72    71  Female   98.0  Strong    Kolkata       Yes      11.0
73    80  Female   98.0    Mild      Delhi       Yes       5.0
74    13  Female  100.0  Strong    Kolkata        No      49.0
75    23    Male    NaN    Mild     Mumbai        No      40.0
77    33  Female  102.0  Strong      Delhi        No      34.0
78    16    Male  104.0    Mild    Kolkata        No      46.0
79    34  Female    NaN  Strong     Mumbai       Yes      33.0
80    15    Male  101.0    Mild      Delhi       Yes      47.0
81    83    Male  103.0    Mild    Kolkata        No       2.0
83    26  Female   98.0    Mild    Kolkata        No      37.0
84    74    Male  102.0    Mild     Mumbai       Yes       8.0
85    82  Female  102.0  Strong  Bangalore        No       3.0
86    38  Female  101.0    Mild  Bangalore        No      32.0
87    55    Male  100.0    Mild    Kolkata        No      21.0
88    49  Female  101.0    Mild      Delhi       Yes      25.0
89    50  Female  103.0    Mild    Kolkata        No      24.0
93    22  Female   99.0    Mild  Bangalore       Yes      41.0
95    72    Male   99.0    Mild  Bangalore        No      10.0
97    18  Female  104.0    Mild  Bangalore        No      44.0
98    66    Male   99.0  Strong  Bangalore        No      15.0
99    44    Male  104.0    Mild     Mumbai        No      29.0
101   11  Female  100.0  Strong    Kolkata       Yes      51.0
102   47  Female  100.0  Strong  Bangalore       Yes      27.0
105   81  Female  101.0    Mild     Mumbai       Yes       4.0
109    6  Female  104.0    Mild    Kolkata       Yes      54.0
110   24  Female  102.0  Strong  Bangalore       Yes      39.0
112   56  Female  104.0  Strong  Bangalore       Yes      20.0
113   10    Male  100.0    Mild  Bangalore        No      52.0
118   54  Female  104.0  Strong    Kolkata        No      22.0
120   68  Female  101.0  Strong      Delhi        No      14.0
125    5    Male  102.0    Mild    Kolkata       Yes      55.0
127    8  Female  101.0    Mild    Kolkata        No      53.0
129   48  Female  103.0    Mild    Kolkata       Yes      26.0
133   17  Female  104.0    Mild    Kolkata        No      45.0
139   46    Male  103.0  Strong  Bangalore        No      28.0
140   59  Female   99.0  Strong      Delhi        No      19.0
144   79    Male    NaN  Strong    Kolkata       Yes       6.0