In [28]:
import pandas as pd

df = pd.DataFrame({
    "Student_ID": [
        101, 102, 103, 104, 105,
        106, 107, 108, 109, 110,
        111, 112, 113, 114, 115
    ],

    "Student_Name": [
        "Aarav", "Riya", "Neha", "Rahul", "Priya",
        "Aman", "Kavya", "Rohit", "Simran", "Vikas",
        "Anjali", "Karan", "Meera", "Arjun", "Nisha"
    ],

    "DOB": [
        "2006-01-15", "2005-03-20", "2006-06-10",
        "2005-09-25", "2006-02-12", "2005-11-30",
        "2006-04-18", "2005-07-22", "2006-08-05",
        "2005-12-17", "2006-10-28", "2005-05-11",
        "2006-12-20", "2005-01-08", "2006-07-14"
    ],

    "Admission_Date": [
        "2024-07-10", "2024-07-12", "2024-07-15",
        "2024-07-18", "2024-07-20", "2024-07-22",
        "2024-07-25", "2024-07-28", "2024-08-01",
        "2024-08-03", "2024-08-05", "2024-08-08",
        "2024-08-10", "2024-08-12", "2024-08-15"
    ],

    "Course": [
        "Python", "SQL", "Python", "Power BI", "SQL",
        "Python", "Excel", "Power BI", "Python", "SQL",
        "Excel", "Python", "Power BI", "SQL", "Python"
    ],

    "Marks": [
        78, 85, 92, 67, 74,
        88, 95, 61, 83, 72,
        90, 56, 81, 69, 97
    ],

    "Attendance": [
        92, 88, 95, 76, 84,
        91, 98, 72, 89, 81,
        94, 68, 87, 79, 96
    ],

    "Study_Hours": [
        3, 4, 5, 2, 3,
        4, 6, 2, 4, 3,
        5, 2, 4, 3, 6
    ],

    "Fees_Paid": [
        15000, 18000, 15000, 20000, 18000,
        15000, 12000, 20000, 15000, 18000,
        12000, 15000, 20000, 18000, 15000
    ]
})

print(df)

    Student_ID Student_Name         DOB Admission_Date    Course  Marks  \
0          101        Aarav  2006-01-15     2024-07-10    Python     78
1          102         Riya  2005-03-20     2024-07-12       SQL     85
2          103         Neha  2006-06-10     2024-07-15    Python     92
3          104        Rahul  2005-09-25     2024-07-18  Power BI     67
4          105        Priya  2006-02-12     2024-07-20       SQL     74
5          106         Aman  2005-11-30     2024-07-22    Python     88
6          107        Kavya  2006-04-18     2024-07-25     Excel     95
7          108        Rohit  2005-07-22     2024-07-28  Power BI     61
8          109       Simran  2006-08-05     2024-08-01    Python     83
9          110        Vikas  2005-12-17     2024-08-03       SQL     72
10         111       Anjali  2006-10-28     2024-08-05     Excel     90
11         112        Karan  2005-05-11     2024-08-08    Python     56
12         113        Meera  2006-12-20     2024-08-10  Power BI     81
13         114        Arjun  2005-01-08     2024-08-12       SQL     69
14         115        Nisha  2006-07-14     2024-08-15    Python     97

    Attendance  Study_Hours  Fees_Paid
0           92            3      15000
1           88            4      18000
2           95            5      15000
3           76            2      20000
4           84            3      18000
5           91            4      15000
6           98            6      12000
7           72            2      20000
8           89            4      15000
9           81            3      18000
10          94            5      12000
11          68            2      15000
12          87            4      20000
13          79            3      18000
14          96            6      15000

In [6]:
df[['Marks','Attendance']]

    Marks  Attendance
0      78          92
1      85          88
2      92          95
3      67          76
4      74          84
5      88          91
6      95          98
7      61          72
8      83          89
9      72          81
10     90          94
11     56          68
12     81          87
13     69          79
14     97          96

In [12]:
df1 = df [['Student_ID', 'Student_Name', 'Course']]
df1

    Student_ID Student_Name    Course
0          101        Aarav    Python
1          102         Riya       SQL
2          103         Neha    Python
3          104        Rahul  Power BI
4          105        Priya       SQL
5          106         Aman    Python
6          107        Kavya     Excel
7          108        Rohit  Power BI
8          109       Simran    Python
9          110        Vikas       SQL
10         111       Anjali     Excel
11         112        Karan    Python
12         113        Meera  Power BI
13         114        Arjun       SQL
14         115        Nisha    Python

In [15]:
df[(df['Course'] == 'Python') & (df ['Marks'] > 70)]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [18]:
df[df['Course'].isin(['Python', 'SQL'])]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [21]:
df.sort_values(['Marks'], ascending = False )

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000

In [24]:
df.nlargest(5, 'Marks')

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000

In [27]:
df.nsmallest(5, 'Marks')

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000

In [35]:
# assignment que 
# Select the rows of students with Student_ID from 103 to 107 using loc.
df.loc[2 : 6]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000

In [43]:
# Select only the Student_Name, Course, and Marks columns using loc.
df.loc[:, ['Student_Name', 'Course', 'Marks']]

   Student_Name    Course  Marks
0         Aarav    Python     78
1          Riya       SQL     85
2          Neha    Python     92
3         Rahul  Power BI     67
4         Priya       SQL     74
5          Aman    Python     88
6         Kavya     Excel     95
7         Rohit  Power BI     61
8        Simran    Python     83
9         Vikas       SQL     72
10       Anjali     Excel     90
11        Karan    Python     56
12        Meera  Power BI     81
13        Arjun       SQL     69
14        Nisha    Python     97

In [45]:
# Display the Student_Name and Marks of students whose index is 2 to 6.
df.loc[2:6, ["Student_Name", "Marks"]]

  Student_Name  Marks
2         Neha     92
3        Rahul     67
4        Priya     74
5         Aman     88
6        Kavya     95

In [47]:
# Using loc, display the complete record of the student whose index is 10.
df.loc[10]

Student_ID               111
Student_Name          Anjali
DOB               2006-10-28
Admission_Date    2024-08-05
Course                 Excel
Marks                     90
Attendance                94
Study_Hours                5
Fees_Paid              12000
Name: 10, dtype: object

In [49]:
# Select rows from index 5 to 10 and columns from Course to Study_Hours.
df.loc[5:10, "Course":"Study_Hours"]

      Course  Marks  Attendance  Study_Hours
5     Python     88          91            4
6      Excel     95          98            6
7   Power BI     61          72            2
8     Python     83          89            4
9        SQL     72          81            3
10     Excel     90          94            5

In [54]:
# Display the first 5 rows using iloc.
df.iloc[:5]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000

In [55]:
# Display the last 5 rows using iloc.
df.iloc[-5:]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [57]:
# Select the Student_Name and Marks columns for all students using iloc.
df.iloc[:, [1, 5]]

   Student_Name  Marks
0         Aarav     78
1          Riya     85
2          Neha     92
3         Rahul     67
4         Priya     74
5          Aman     88
6         Kavya     95
7         Rohit     61
8        Simran     83
9         Vikas     72
10       Anjali     90
11        Karan     56
12        Meera     81
13        Arjun     69
14        Nisha     97

In [82]:
# Display rows 3 to 7 and columns Student_Name to Attendance using iloc.
df.iloc[3:8, 1:7]

  Student_Name         DOB Admission_Date    Course  Marks  Attendance
3        Rahul  2005-09-25     2024-07-18  Power BI     67          76
4        Priya  2006-02-12     2024-07-20       SQL     74          84
5         Aman  2005-11-30     2024-07-22    Python     88          91
6        Kavya  2006-04-18     2024-07-25     Excel     95          98
7        Rohit  2005-07-22     2024-07-28  Power BI     61          72

In [62]:
# Display the data of the student at index position 8 using iloc.
df.iloc[8]

Student_ID               109
Student_Name          Simran
DOB               2006-08-05
Admission_Date    2024-08-01
Course                Python
Marks                     83
Attendance                89
Study_Hours                4
Fees_Paid              15000
Name: 8, dtype: object

In [64]:
# Select every second row from the dataset using iloc.
df.iloc[::2]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [83]:
# Find all students who scored more than 80 marks.
df[df["Marks"] > 80]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [85]:
# Find students whose attendance is below 80%.
df[df["Attendance"] < 80]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000

In [86]:
# Find students who are enrolled in the Python course.
df[df["Course"] == "Python"]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [87]:
# Find students who are enrolled in Python or SQL.
df[df["Course"].isin(["Python", "SQL"])]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [88]:
# Find students who scored more than 75 marks and have attendance above 85%
df[(df["Marks"] > 75) & (df["Attendance"] > 85)]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [89]:
# Find students whose Study_Hours are 4 or more.
df[(df["Study_Hours"] >= 4)]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [79]:
# Find students who paid ₹15,000 in fees.
df[df['Fees_Paid'] == 15000]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [ ]:
# Find students whose marks are between 70 and 90.
df[df["Marks"].between(70, 90)]

    Student_ID Student_Name         DOB Admission_Date    Course  Marks  \
0          101        Aarav  2006-01-15     2024-07-10    Python     78
1          102         Riya  2005-03-20     2024-07-12       SQL     85
4          105        Priya  2006-02-12     2024-07-20       SQL     74
5          106         Aman  2005-11-30     2024-07-22    Python     88
8          109       Simran  2006-08-05     2024-08-01    Python     83
9          110        Vikas  2005-12-17     2024-08-03       SQL     72
10         111       Anjali  2006-10-28     2024-08-05     Excel     90
12         113        Meera  2006-12-20     2024-08-10  Power BI     81

    Attendance  Study_Hours  Fees_Paid
0           92            3      15000
1           88            4      18000
4           84            3      18000
5           91            4      15000
8           89            4      15000
9           81            3      18000
10          94            5      12000
12          87            4      20000

In [ ]:
# Find students who are not enrolled in Python.
df[df["Course"] != "Python"]

    Student_ID Student_Name         DOB Admission_Date    Course  Marks  \
1          102         Riya  2005-03-20     2024-07-12       SQL     85
3          104        Rahul  2005-09-25     2024-07-18  Power BI     67
4          105        Priya  2006-02-12     2024-07-20       SQL     74
6          107        Kavya  2006-04-18     2024-07-25     Excel     95
7          108        Rohit  2005-07-22     2024-07-28  Power BI     61
9          110        Vikas  2005-12-17     2024-08-03       SQL     72
10         111       Anjali  2006-10-28     2024-08-05     Excel     90
12         113        Meera  2006-12-20     2024-08-10  Power BI     81
13         114        Arjun  2005-01-08     2024-08-12       SQL     69

    Attendance  Study_Hours  Fees_Paid
1           88            4      18000
3           76            2      20000
4           84            3      18000
6           98            6      12000
7           72            2      20000
9           81            3      18000
10          94            5      12000
12          87            4      20000
13          79            3      18000

In [ ]:
# Find students who have attendance below 80% OR marks below 70.
df[(df["Attendance"] < 80) | (df["Marks"] < 70)]

    Student_ID Student_Name         DOB Admission_Date    Course  Marks  \
3          104        Rahul  2005-09-25     2024-07-18  Power BI     67
7          108        Rohit  2005-07-22     2024-07-28  Power BI     61
11         112        Karan  2005-05-11     2024-08-08    Python     56
13         114        Arjun  2005-01-08     2024-08-12       SQL     69

    Attendance  Study_Hours  Fees_Paid
3           76            2      20000
7           72            2      20000
11          68            2      15000
13          79            3      18000

In [ ]:
# Sort the dataset by Marks in ascending order.
df.sort_values(by="Marks", ascending=True)

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [ ]:
# Sort the dataset by Marks in descending order.
df.sort_values(by="Marks", ascending=False)

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000

In [101]:
# Sort students by Attendance from highest to lowest.
df.sort_values(by="Attendance", ascending=False)

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000

In [103]:
# Sort the dataset by Study_Hours in ascending order.
df.sort_values(by="Study_Hours", ascending=True)

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000

In [105]:
# Sort the dataset first by Course and then by Marks in descending order.
df.sort_values(
    by=["Course", "Marks"],
    ascending=[True, False]
)        # chat gpt

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000

In [107]:
# Find the top 5 students based on Marks using sorting.
df.sort_values(by="Marks", ascending=False).head(5)

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000

In [109]:
# Sort students by Fees_Paid in descending order.
df.sort_values(by="Fees_Paid", ascending=False)

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
3,104,Rahul,2005-09-25,2024-07-18,Power BI,67,76,2,20000
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61,72,2,20000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81,87,4,20000
1,102,Riya,2005-03-20,2024-07-12,SQL,85,88,4,18000
4,105,Priya,2006-02-12,2024-07-20,SQL,74,84,3,18000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72,81,3,18000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69,79,3,18000
0,101,Aarav,2006-01-15,2024-07-10,Python,78,92,3,15000
2,103,Neha,2006-06-10,2024-07-15,Python,92,95,5,15000
5,106,Aman,2005-11-30,2024-07-22,Python,88,91,4,15000
8,109,Simran,2006-08-05,2024-08-01,Python,83,89,4,15000
11,112,Karan,2005-05-11,2024-08-08,Python,56,68,2,15000
14,115,Nisha,2006-07-14,2024-08-15,Python,97,96,6,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95,98,6,12000
10,111,Anjali,2006-10-28,2024-08-05,Excel,90,94,5,12000

In [113]:
# First, assume the following missing values are added:
# df.loc[3, "Marks"] = None
# df.loc[7, "Attendance"] = None
# df.loc[10, "Course"] = None
df.loc[3, "Marks"] = None
df.loc[7, "Attendance"] = None
df.loc[10, "Course"] = None

In [115]:
# Check whether the dataset contains any missing values.
df.isnull().values.any()

np.True_

In [117]:
# Find the number of missing values in each column.
df.isnull().sum()

Student_ID        0
Student_Name      0
DOB               0
Admission_Date    0
Course            1
Marks             1
Attendance        1
Study_Hours       0
Fees_Paid         0
dtype: int64

In [119]:
# Find the total number of missing values in the entire dataset.
df.isnull().sum().sum()

np.int64(3)

In [121]:
# Display the rows where Marks is missing.
df[df["Marks"].isnull()]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
3,104,Rahul,2005-09-25,2024-07-18,Power BI,NaN,76.0,2,20000

In [ ]:
# Display the rows where Attendance is missing.
df[df["Attendance"].isnull()]

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
7,108,Rohit,2005-07-22,2024-07-28,Power BI,61.0,NaN,2,20000

In [125]:
# Replace missing values in Marks with the mean Marks.
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [127]:
# Replace missing values in Course with "Unknown".
df["Course"] = df["Course"].fillna("Unknown")

In [132]:
# Remove rows containing any missing values.
# df_clean = df.dropna()

# print(df_clean)       # chatgpt
df.dropna()

,Student_ID,Student_Name,DOB,Admission_Date,Course,Marks,Attendance,Study_Hours,Fees_Paid
0,101,Aarav,2006-01-15,2024-07-10,Python,78.000000,92.0,3,15000
1,102,Riya,2005-03-20,2024-07-12,SQL,85.000000,88.0,4,18000
2,103,Neha,2006-06-10,2024-07-15,Python,92.000000,95.0,5,15000
3,104,Rahul,2005-09-25,2024-07-18,Power BI,80.071429,76.0,2,20000
4,105,Priya,2006-02-12,2024-07-20,SQL,74.000000,84.0,3,18000
5,106,Aman,2005-11-30,2024-07-22,Python,88.000000,91.0,4,15000
6,107,Kavya,2006-04-18,2024-07-25,Excel,95.000000,98.0,6,12000
8,109,Simran,2006-08-05,2024-08-01,Python,83.000000,89.0,4,15000
9,110,Vikas,2005-12-17,2024-08-03,SQL,72.000000,81.0,3,18000
10,111,Anjali,2006-10-28,2024-08-05,Unknown,90.000000,94.0,5,12000
11,112,Karan,2005-05-11,2024-08-08,Python,56.000000,68.0,2,15000
12,113,Meera,2006-12-20,2024-08-10,Power BI,81.000000,87.0,4,20000
13,114,Arjun,2005-01-08,2024-08-12,SQL,69.000000,79.0,3,18000
14,115,Nisha,2006-07-14,2024-08-15,Python,97.000000,96.0,6,15000