In [6]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Priya", "Rahul", "Neha", "Aman", "Priya", "Rahul", "Neha"],
    "City" : ["Jaipur", "Sikar", "Sikar", "Delhi", "Jaipur", "Sikar", "Sikar", "Jaipur"],
    "Department": ["IT", "HR", "IT", "HR", "IT", "HR", "Sales", "Sales"],
    "Salary": [25000, 30000, 35000, 28000, 40000, 32000, 27000, 36000],
    "Age": [22, 25, 24, 23, 26, 27, 22, 24]
})

print(df)

    Name    City Department  Salary  Age
0   Aman  Jaipur         IT   25000   22
1  Priya   Sikar         HR   30000   25
2  Rahul   Sikar         IT   35000   24
3   Neha   Delhi         HR   28000   23
4   Aman  Jaipur         IT   40000   26
5  Priya   Sikar         HR   32000   27
6  Rahul   Sikar      Sales   27000   22
7   Neha  Jaipur      Sales   36000   24

In [8]:
df.groupby(['Department', 'City'])['Salary'].sum()

Department  City
HR          Delhi     28000
            Sikar     62000
IT          Jaipur    65000
            Sikar     35000
Sales       Jaipur    36000
            Sikar     27000
Name: Salary, dtype: int64

In [11]:
a = df.groupby(['Department', 'City'])['Salary'].agg(['sum', 'mean', 'max'])
a

                     sum     mean    max
Department City
HR         Delhi   28000  28000.0  28000
           Sikar   62000  31000.0  32000
IT         Jaipur  65000  32500.0  40000
           Sikar   35000  35000.0  35000
Sales      Jaipur  36000  36000.0  36000
           Sikar   27000  27000.0  27000

In [13]:
df.groupby(['Department', 'City']).agg({
    "Salary": "sum",
    "Salary": "mean"
})

                    Salary
Department City
HR         Delhi   28000.0
           Sikar   31000.0
IT         Jaipur  32500.0
           Sikar   35000.0
Sales      Jaipur  36000.0
           Sikar   27000.0

In [15]:
import pandas as pd

df1 = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Palak", "Priya", "Akshya", "Ayush", "Neha"],
    "Branch": ["CSE", "IT", "CSE", "AI", "IT"]
})

print(df1)

   Student_ID    Name Branch
0         101   Palak    CSE
1         102   Priya     IT
2         103  Akshya    CSE
3         104   Ayush     AI
4         105    Neha     IT

In [17]:
df2 = pd.DataFrame({
    "Student_ID": [101, 102, 103, 106, 107],
    "Marks": [85, 90, 78, 88, 92],
    "City": ["Sikar", "Jaipur", "Bikaner", "Delhi", "Ajmer"]
})

print(df2)

   Student_ID  Marks     City
0         101     85    Sikar
1         102     90   Jaipur
2         103     78  Bikaner
3         106     88    Delhi
4         107     92    Ajmer

In [23]:
pd.merge(df1, df2, on = 'Student_ID', how= 'left')

   Student_ID    Name Branch  Marks     City
0         101   Palak    CSE   85.0    Sikar
1         102   Priya     IT   90.0   Jaipur
2         103  Akshya    CSE   78.0  Bikaner
3         104   Ayush     AI    NaN      NaN
4         105    Neha     IT    NaN      NaN